In [2]:
import numpy as np
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
tickers = ["^GSPC", "^IXIC"]  # S&P 500 and Nasdaq Composite

data = yf.download(
    tickers=tickers,
    period="60d",
    interval="5m",
    auto_adjust=True,
    group_by="ticker",
    progress=True
)

[*********************100%***********************]  2 of 2 completed

In [9]:
# implikowanej
ticker = yf.Ticker("AAPL")
options_chain = ticker.option_chain(ticker.options[0])
print(options_chain.calls[['strike', 'impliedVolatility']])

    strike  impliedVolatility
0    250.0           1.185551
1    255.0           1.689943
2    260.0           0.847658
3    265.0           0.830080
4    275.0           1.201908
5    280.0           0.503911
6    285.0           0.587895
7    290.0           0.592289
8    295.0           0.673343
9    300.0           0.502202
10   305.0           0.237312
11   310.0           0.155526
12   315.0           0.140878
13   320.0           0.167977
14   325.0           0.205086
15   330.0           0.257820
16   335.0           0.316413
17   340.0           0.390631
18   345.0           0.529302

In [4]:
tickers = ["^GSPC", "^IXIC", "^VIX"]

data = yf.download(
    tickers,
    start="2020-01-01",
    end="2025-01-01",
    auto_adjust=True
)

data.head()

[*********************100%***********************]  3 of 3 completed

Price             Close                             High               \
Ticker            ^GSPC        ^IXIC   ^VIX        ^GSPC        ^IXIC
Date
2020-01-02  3257.850098  9092.190430  12.47  3258.139893  9093.429688
2020-01-03  3234.850098  9020.769531  14.02  3246.149902  9065.759766
2020-01-06  3246.280029  9071.469727  13.85  3246.840088  9072.410156
2020-01-07  3237.179932  9068.580078  13.79  3244.909912  9091.929688
2020-01-08  3253.050049  9129.240234  13.45  3267.070068  9168.889648

Price                          Low                             Open  \
Ticker           ^VIX        ^GSPC        ^IXIC   ^VIX        ^GSPC
Date
2020-01-02  13.720000  3235.530029  9010.889648  12.42  3244.669922
2020-01-03  16.200001  3222.340088  8976.429688  13.13  3226.360107
2020-01-06  16.389999  3214.639893  8943.500000  13.54  3217.550049
2020-01-07  14.460000  3232.429932  9042.549805  13.39  3241.860107
2020-01-08  15.240000  3236.669922  9059.379883  12.83  3238.590088

Price                               Volume
Ticker            ^IXIC   ^VIX       ^GSPC       ^IXIC ^VIX
Date
2020-01-02  9039.459961  13.46  3459930000  2862700000    0
2020-01-03  8976.429688  15.01  3484700000  2586520000    0
2020-01-06  8943.500000  15.45  3702460000  2810450000    0
2020-01-07  9076.639648  13.84  3435910000  2381740000    0
2020-01-08  9068.030273  15.16  3726840000  2472620000    0

In [7]:
data

Price             Close                              High                \
Ticker            ^GSPC         ^IXIC   ^VIX        ^GSPC         ^IXIC
Date
2020-01-02  3257.850098   9092.190430  12.47  3258.139893   9093.429688
2020-01-03  3234.850098   9020.769531  14.02  3246.149902   9065.759766
2020-01-06  3246.280029   9071.469727  13.85  3246.840088   9072.410156
2020-01-07  3237.179932   9068.580078  13.79  3244.909912   9091.929688
2020-01-08  3253.050049   9129.240234  13.45  3267.070068   9168.889648
...                 ...           ...    ...          ...           ...
2024-12-24  6040.040039  20031.130859  14.27  6040.100098  20031.130859
2024-12-26  6037.589844  20020.359375  14.73  6049.750000  20070.080078
2024-12-27  5970.839844  19722.029297  15.95  6006.169922  19904.769531
2024-12-30  5906.939941  19486.789062  17.40  5940.790039  19622.929688
2024-12-31  5881.629883  19310.789062  17.35  5929.740234  19563.720703

Price                          Low                                  Open  \
Ticker           ^VIX        ^GSPC         ^IXIC       ^VIX        ^GSPC
Date
2020-01-02  13.720000  3235.530029   9010.889648  12.420000  3244.669922
2020-01-03  16.200001  3222.340088   8976.429688  13.130000  3226.360107
2020-01-06  16.389999  3214.639893   8943.500000  13.540000  3217.550049
2020-01-07  14.460000  3232.429932   9042.549805  13.390000  3241.860107
2020-01-08  15.240000  3236.669922   9059.379883  12.830000  3238.590088
...               ...          ...           ...        ...          ...
2024-12-24  17.040001  5981.439941  19813.759766  14.270000  5984.629883
2024-12-26  15.930000  6007.370117  19888.109375  14.550000  6024.970215
2024-12-27  18.450001  5932.950195  19553.400391  15.290000  6006.169922
2024-12-30  19.219999  5869.160156  19342.509766  16.440001  5920.669922
2024-12-31  17.809999  5868.859863  19283.410156  16.680000  5919.740234

Price                                    Volume
Ticker             ^IXIC       ^VIX       ^GSPC       ^IXIC ^VIX
Date
2020-01-02   9039.459961  13.460000  3459930000  2862700000    0
2020-01-03   8976.429688  15.010000  3484700000  2586520000    0
2020-01-06   8943.500000  15.450000  3702460000  2810450000    0
2020-01-07   9076.639648  13.840000  3435910000  2381740000    0
2020-01-08   9068.030273  15.160000  3726840000  2472620000    0
...                  ...        ...         ...         ...  ...
2024-12-24  19818.480469  16.969999  1757720000  4739190000    0
2024-12-26  19979.250000  14.990000  2904530000  6467910000    0
2024-12-27  19896.769531  15.380000  3159610000  7765120000    0
2024-12-30  19460.410156  17.209999  3433250000  8384090000    0
2024-12-31  19551.359375  17.389999  3128350000  8873030000    0

[1258 rows x 15 columns]

In [ ]:
def compute_rv(data, ticker):
    # Pobranie danych dla konkretnego tickera z MultiIndex
    df = data[ticker].copy()
    df['log_close'] = np.log(df['Close'])
    df["Ret_1d"] = df["log_close"].diff()
    df["RV_5d"] = df["Ret_1d"].rolling(5).std()
    df["RV_22d"] = df['Ret_1d'].rolling(22).std()
    return df

In [14]:
data.columns

MultiIndex([( 'Close', '^GSPC'),
            ( 'Close', '^IXIC'),
            ( 'Close',  '^VIX'),
            (  'High', '^GSPC'),
            (  'High', '^IXIC'),
            (  'High',  '^VIX'),
            (   'Low', '^GSPC'),
            (   'Low', '^IXIC'),
            (   'Low',  '^VIX'),
            (  'Open', '^GSPC'),
            (  'Open', '^IXIC'),
            (  'Open',  '^VIX'),
            ('Volume', '^GSPC'),
            ('Volume', '^IXIC'),
            ('Volume',  '^VIX')],
           names=['Price', 'Ticker'])

In [15]:
rv_sp500 = compute_rv(data=data, ticker='^GSPC')
rv_ixic = compute_rv(data=data, ticker='^IXIC')
rv_vix = compute_rv(data=data, ticker='^VIX')

KeyError: '^GSPC'

In [5]:
rv_sp500

            ^GSPC_RV
date
2026-03-05  0.000083
2026-03-06  0.000087
2026-03-09  0.000121
2026-03-10  0.000064
2026-03-11  0.000058
2026-03-12  0.000068
2026-03-13  0.000065
2026-03-16  0.000043
2026-03-17  0.000021
2026-03-18  0.000043
2026-03-19  0.000076
2026-03-20  0.000072
2026-03-23  0.000090
2026-03-24  0.000073
2026-03-25  0.000055
2026-03-26  0.000047
2026-03-27  0.000057
2026-03-30  0.000063
2026-03-31  0.000127
2026-04-01  0.000036
2026-04-02  0.000116
2026-04-06  0.000039
2026-04-07  0.000081
2026-04-08  0.000041
2026-04-09  0.000033
2026-04-10  0.000014
2026-04-13  0.000027
2026-04-14  0.000016
2026-04-15  0.000027
2026-04-16  0.000029
2026-04-17  0.000020
2026-04-20  0.000017
2026-04-21  0.000062
2026-04-22  0.000015
2026-04-23  0.000058
2026-04-24  0.000017
2026-04-27  0.000014
2026-04-28  0.000015
2026-04-29  0.000026
2026-04-30  0.000024
2026-05-01  0.000020
2026-05-04  0.000032
2026-05-05  0.000010
2026-05-06  0.000011
2026-05-07  0.000032
2026-05-08  0.000011
2026-05-11  0.000013
2026-05-12  0.000028
2026-05-13  0.000019
2026-05-14  0.000018
2026-05-15  0.000045
2026-05-18  0.000080
2026-05-19  0.000053
2026-05-20  0.000036
2026-05-21  0.000055
2026-05-22  0.000019
2026-05-26  0.000013
2026-05-27  0.000021
2026-05-28  0.000021
2026-05-29  0.000019